name: Actualizar HTML horario

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Instalar Dependencias del Mundial
      run: pip install requests feedparser

    - name: Generar Base de Conocimiento
      run: python generar_html.py
      
    - name: Auto Commit y Push del HTML
      # 👇 Aquí configuramos la zona horaria para todo este bloque de pasos
      env:
        TZ: 'America/Argentina/Buenos_Aires'
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # 1. Agregamos el archivo HTML que generó el script de Python
        git add mundial.html
        
        # 2. Hacemos el commit con la hora local correcta en el mensaje
        git commit -m "Actualización automática: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No hay cambios en mundial.html para commitear"
        
        # 3. Traemos tus últimos cambios locales de forma segura
        git pull --rebase origin main
        
        # 4. Subimos todo limpio a GitHub
        git push origin main
